### ISSUE TITLE
Get blank page after click on "change attribute set"

### ISSUE THREAD

**Issue by raqlo** [ibnab/magento2-extension-change-attribute-set#2]
Everytime I try to select any product of the catalog, it doesn't matter the quantity, it asks me if I i want to change the attribute set and then I get into a blank page and doesn't change a thing.

The url of the blank page I get `https://mydomain.com/admin_admin/changeattributeset/product/massChangeattributeset/changeattributeset/10/key/b3f7912fdfa6226c8e3c0b33a0a8575a7d7fbf2752742148603e22d2cd7cfad9/
`
I'm currently using Magento 2.0.7

**Comment by ibnab** [comment]
plz download from
http://store.ibnab.com/magento-2-extensions/change-attribute-set.html
